### ISSUE TITLE
Access to Baidu's original dataset

### ISSUE THREAD

**Issue by GauravBh1010tt** [philipphager/ultr-reproducibility#28]
Hey Phillipp,

Thanks for the code base. Do you have access to Baidu's original dataset? The download links are not working anymore. 

Best,
Gaurav

**Comment by philipphager** [comment]
Dear Gaurav,

I realized I've never answered here but just via email. So just for completeness. As the [Baidu-ULTR dataset](https://searchscience.baidu.com/dataset.html) seems to have been taken offline, we uploaded the excerpt of the original dataset that we used to pre-train our models here: https://huggingface.co/datasets/philipphager/baidu-ultr-pretrain/tree/main
